"""Changes in TradeList table

Revision ID: 7400b00e0fa6
Revises: ec176772a53d
Create Date: 2024-12-14 13:10:45.760788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7400b00e0fa6'
down_revision: Union[str, None] = 'ec176772a53d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('account_ibfk_2', 'account', type_='foreignkey')
    op.create_foreign_key(None, 'account', 'currency', ['currency_id'], ['currency_id'])
    op.drop_constraint('role_ibfk_2', 'role', type_='foreignkey')
    op.create_foreign_key(None, 'role', 'currency', ['currency_id'], ['currency_id'])
    op.add_column('trade_list', sa.Column('order_type', sa.Enum('LIMIT', 'MARKET', 'P2P', name='ordertype'), nullable=False))
    op.add_column('trade_list', sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CANCELED', name='tradestatus'), nullable=False))
    op.add_column('trade_list', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('trade_list', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('trade_list', sa.Column('executed_at', sa.DateTime(), nullable=True))
    op.add_column('trade_list', sa.Column('executed_price', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('trade_list', sa.Column('recipient_discord_id', sa.BigInteger(), nullable=True))
    op.create_index('idx_base_quote_currency', 'trade_list', ['base_currency_id', 'quote_currency_id'], unique=False)
    op.create_index('idx_discord_id', 'trade_list', ['discord_id'], unique=False)
    op.drop_constraint('trade_list_ibfk_4', 'trade_list', type_='foreignkey')
    op.drop_constraint('trade_list_ibfk_3', 'trade_list', type_='foreignkey')
    op.create_foreign_key(None, 'trade_list', 'currency', ['base_currency_id'], ['currency_id'])
    op.create_foreign_key(None, 'trade_list', 'currency', ['quote_currency_id'], ['currency_id'])
    op.drop_constraint('trade_log_ibfk_5', 'trade_log', type_='foreignkey')
    op.drop_constraint('trade_log_ibfk_4', 'trade_log', type_='foreignkey')
    op.create_foreign_key(None, 'trade_log', 'currency', ['quote_currency_id'], ['currency_id'])
    op.create_foreign_key(None, 'trade_log', 'currency', ['base_currency_id'], ['currency_id'])
    op.drop_constraint('transaction_ibfk_5', 'transaction', type_='foreignkey')
    op.drop_constraint('transaction_ibfk_4', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'account', ['sender_account_id'], ['account_id'])
    op.create_foreign_key(None, 'transaction', 'account', ['receiver_account_id'], ['account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_ibfk_4', 'transaction', 'account', ['receiver_account_id'], ['account_id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.create_foreign_key('transaction_ibfk_5', 'transaction', 'account', ['sender_account_id'], ['account_id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.drop_constraint(None, 'trade_log', type_='foreignkey')
    op.drop_constraint(None, 'trade_log', type_='foreignkey')
    op.create_foreign_key('trade_log_ibfk_4', 'trade_log', 'currency', ['base_currency_id'], ['currency_id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.create_foreign_key('trade_log_ibfk_5', 'trade_log', 'currency', ['quote_currency_id'], ['currency_id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.drop_constraint(None, 'trade_list', type_='foreignkey')
    op.drop_constraint(None, 'trade_list', type_='foreignkey')
    op.create_foreign_key('trade_list_ibfk_3', 'trade_list', 'currency', ['base_currency_id'], ['currency_id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.create_foreign_key('trade_list_ibfk_4', 'trade_list', 'currency', ['quote_currency_id'], ['currency_id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.drop_index('idx_discord_id', table_name='trade_list')
    op.drop_index('idx_base_quote_currency', table_name='trade_list')
    op.drop_column('trade_list', 'recipient_discord_id')
    op.drop_column('trade_list', 'executed_price')
    op.drop_column('trade_list', 'executed_at')
    op.drop_column('trade_list', 'updated_at')
    op.drop_column('trade_list', 'created_at')
    op.drop_column('trade_list', 'status')
    op.drop_column('trade_list', 'order_type')
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.create_foreign_key('role_ibfk_2', 'role', 'currency', ['currency_id'], ['currency_id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.create_foreign_key('account_ibfk_2', 'account', 'currency', ['currency_id'], ['currency_id'], onupdate='RESTRICT', ondelete='CASCADE')
    # ### end Alembic commands ###
