"""Fix relationship between Role and Currency

Revision ID: 749a57a04737
Revises: 9c3738b78740
Create Date: 2024-12-08 10:29:27.959805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '749a57a04737'
down_revision: Union[str, None] = '9c3738b78740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('currency_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'role', 'currency', ['currency_id'], ['currency_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_column('role', 'currency_id')
    # ### end Alembic commands ###
