"""Initial tables

Revision ID: 9c3738b78740
Revises: 
Create Date: 2024-12-08 10:23:24.111575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c3738b78740'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('currency_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('currency_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discord_id', sa.Integer(), nullable=False),
    sa.Column('role_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('account',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.currency_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('trade_list',
    sa.Column('trade_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discord_id', sa.Integer(), nullable=False),
    sa.Column('base_currency_id', sa.Integer(), nullable=False),
    sa.Column('quote_currency_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('BUY', 'SELL', name='tradetype'), nullable=False),
    sa.Column('price_offered', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['base_currency_id'], ['currency.currency_id'], ),
    sa.ForeignKeyConstraint(['quote_currency_id'], ['currency.currency_id'], ),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_table('trade_log',
    sa.Column('trade_log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_currency_id', sa.Integer(), nullable=False),
    sa.Column('quote_currency_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('date_traded', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_currency_id'], ['currency.currency_id'], ),
    sa.ForeignKeyConstraint(['quote_currency_id'], ['currency.currency_id'], ),
    sa.PrimaryKeyConstraint('trade_log_id')
    )
    op.create_index('idx_date_traded', 'trade_log', ['date_traded'], unique=False)
    op.create_table('transaction',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('sender_account_id', sa.Integer(), nullable=False),
    sa.Column('receiver_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_account_id'], ['account.account_id'], ),
    sa.ForeignKeyConstraint(['sender_account_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_index('idx_date_traded', table_name='trade_log')
    op.drop_table('trade_log')
    op.drop_table('trade_list')
    op.drop_table('account')
    op.drop_table('role')
    op.drop_table('currency')
    # ### end Alembic commands ###
